app/tntitem/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Forms for the items."""

from flask_wtf import FlaskForm
from wtforms import HiddenField, TextField, TextAreaField
from wtforms.validators import DataRequired, Optional, Regexp
from app.tntitem.utils import date_to_ts
from app import app

class SearchForm(FlaskForm):
    """Search form."""

    keyword = TextField(
        'Keyword'
    )
    tags = TextField(
        'Tags',
        id='input-tags',
    )
    place = TextField(
        'Place',
        id='address-autocomplete',
    )
    event_start = HiddenField(
        'event_start',
        id='event_start',
        validators=[Optional(), Regexp(r'\d{4}[-/]\d{2}[-/]\d{2}')]
    )
    event_end = HiddenField(
        'event_end',
        id='event_end',
        validators=[Optional(), Regexp(r'\d{4}[-/]\d{2}[-/]\d{2}')]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(SearchForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        initial_validation = super(SearchForm, self).validate()

        if not initial_validation:
            app.logger.debug(self.errors)
            return False

        if (self.keyword.data == "" and
                self.place.data == "" and
                self.tags.data == "" and
                self.event_start.data == ""):
            return False

        if self.event_start.data is not None:
            self.event_start.data = date_to_ts(str(self.event_start.data))
        if self.event_end.data is not None:
            self.event_end.data = date_to_ts(str(self.event_end.data))

        return True


class EditForm(FlaskForm):
    """Search form."""

    iditem = HiddenField('iditem')
    title = TextField(
        'Title',
        validators=[DataRequired()]
    )
    body = TextAreaField(
        'Description',
        validators=[Optional()]
    )
    tags = TextField(
        'Tags',
        validators=[Optional()]
    )
    event_start = TextField(
        'event_start',
        validators=[DataRequired()]
    )
    event_end = TextField(
        'event_end',
        validators=[Optional()]
    )
    latitude = HiddenField(
        'lat',
        validators=[DataRequired()]
    )
    longitude = HiddenField(
        'lon',
        validators=[DataRequired()]
    )
    images = HiddenField(
        'images',
        validators=[DataRequired()]
    )
    location = TextField(
        'location',
        id='address-autocomplete',
        validators=[DataRequired()]
    )
    instagram_id = HiddenField(
        'instagram_id',
        validators=[Optional()]
    )
    unsplash_id = HiddenField(
        'unsplash_id',
        validators=[Optional()]
    )
    original_url = HiddenField(
        'original_url',
        validators=[Optional()]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(EditForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        initial_validation = super(EditForm, self).validate()

        if not initial_validation:
            app.logger.debug(self.errors)
            return False

        if self.event_end.data is None:
            self.event_end.data = self.event_start.data

        return True


class DeleteForm(FlaskForm):
    """Delete form."""

    iditem = HiddenField('iditem')

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(DeleteForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        initial_validation = super(DeleteForm, self).validate()

        if not initial_validation:
            app.logger.debug(self.errors)
            return False

        return True

app/tntitem/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the items actions
"""

# all the imports
import math
from flask import Blueprint, render_template, redirect, url_for, jsonify, flash, g, request, escape, session, make_response
from flask_login import login_required
from app.tntitem.models import TntItems, TntItem, TntItemComment
from app.tntitem.forms import SearchForm, DeleteForm, EditForm
from app.tntuser.models import User
from app.tntitem.utils import sync_insta_items, sync_unsplash_items, enrich_items, get_geocode
from app.resource import db
from app import app

# Define the blueprint: 'maps', set its url prefix: app.url
tntitem = Blueprint(
    'tntitem',
    __name__,
    url_prefix='/item',
    template_folder='templates',
    static_folder='../static')


@tntitem.route('/search', methods=['GET', 'POST'])
def search_items():
    """Function to search a list of items"""
    my_collection = TntItems()
    form = SearchForm(request.args, csrf_enabled=False)
    # this is the result of a real search (from right-pane)
    if form.validate():
        geobounds = {}
        if form.place.data is not None and form.place.data != "":
            geoplace = get_geocode(place=form.place.data)
            if geoplace is not None and len(geoplace) > 0:
                geobounds = geoplace[0]['geometry']['bounds']
        _ = my_collection.search(
            text=form.keyword.data,
            tags=form.tags.data,
            geobounds=geobounds,
            start=form.event_start.data,
            end=form.event_end.data,
            sort='time.start')
    # this is a search from the map display
    else:
        if request.args.get('author') != 'None':
            myAuthor = User.get_by_username(request.args.get('author'))
        else:
            myAuthor = None
        if myAuthor is not None:
            myAuthorId = myAuthor.id
        else:
            myAuthorId = None
        if ('north_east_lat' in request.args and
                'north_east_lng' in request.args and
                'south_west_lat' in request.args and
                'south_west_lng' in request.args):
            geobounds = {
                'northeast':{
                    'lat': float(request.args.get('north_east_lat')),
                    'lng': float(request.args.get('north_east_lng'))
                },
                'southwest': {
                    'lat': float(request.args.get('south_west_lat')),
                    'lng': float(request.args.get('south_west_lng'))
                }
            }
            _ = my_collection.search(
                author=myAuthorId,
                geobounds=geobounds,
                sort='time.start')
        else:
            _ = my_collection.search(
                author=myAuthorId,
                sort='time.start')

    items = enrich_items(items=my_collection.items)
    return jsonify(items)


@tntitem.route('/data_sync')
@login_required
def data_sync():
    """Function to sync data from social accounts with local data"""
    u = User.get_by_id(g.user.id)
    if not u.is_instagram and not u.is_unsplash:
        flash('You need to connect your social account (Instagram/Unsplash)', 'danger')
        return redirect(url_for('tntuser.profile'))
    else:
        response = make_response(redirect(url_for('tntitem.show_items')))
        if u.is_instagram:
            if u.insta_last_id is None:
                response.set_cookie('tour', value="three", path=url_for('tntitem.show_items'))
            task = sync_insta_items.delay(u.id)
            session['instagram_sync_task_id'] = task.id
            flash('Instagram sync started', 'success')
        if u.is_unsplash:
            if u.unsplash_last_id is None:
                response.set_cookie('tour', value="three", path=url_for('tntitem.show_items'))
            task = sync_unsplash_items.delay(u.id)
            session['unsplash_sync_task_id'] = task.id
            flash('Unsplash sync started', 'success')

        return response


@tntitem.route('/instagram_sync') 
def instagram_sync(): 
    """Function to sync instagram account with local data""" 
    u = User.get_by_id(g.user.id) 
    if not u.is_instagram: 
        flash('You need to connect your Instagram account', 'danger') 
        return redirect(url_for('tntuser.profile')) 
    else: 
        response = make_response(redirect(url_for('tntitem.show_items'))) 
        if u.insta_last_id is None: 
            response.set_cookie('tour', value="three", path=url_for('tntitem.show_items')) 
        task = sync_insta_items.delay(u.id) 
        session['instagram_sync_task_id'] = task.id 
        flash('Instagram crawl started', 'success') 
        return response 

@tntitem.route('/unsplash_sync') 
@login_required 
def unsplash_sync(): 
    """Function to sync Unsplash account with local data""" 
    u = User.get_by_id(g.user.id) 
    if not u.is_unsplash: 
        flash('You need to connect your Unsplash account', 'danger') 
        return redirect(url_for('tntuser.profile')) 
    else: 
        response = make_response(redirect(url_for('tntitem.show_items'))) 
        task = sync_unsplash_items.delay(u.id) 
        session['unsplash_sync_task_id'] = task.id 
        flash('Unsplash crawl started', 'success') 
        return response 


@tntitem.route('/instasync_status/<task_id>')
@login_required
def instagram_sync_status(task_id):
    task = sync_insta_items.AsyncResult(task_id)
    if task.state == 'SUCCESS':
        session.pop('instagram_sync_task_id', None)

    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'total': 0,
            'status': 'Pending'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'total': task.info.get('total', 0),
            'status': task.info.get('status', '')
        }
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'total': 0,
            'status': str(task.info),  # this is the exception raised
        }
    return jsonify(response)


@tntitem.route('/unsplasync_status/<task_id>')
@login_required
def unsplash_sync_status(task_id):
    task = sync_unsplash_items.AsyncResult(task_id)
    if task.state == 'SUCCESS':
        session.pop('unsplash_sync_task_id', None)

    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'total': 0,
            'status': 'Pending'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'total': task.info.get('total', 0),
            'status': task.info.get('status', '')
        }
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'total': task.info.get('total', 0),
            'status': str(task.info),  # this is the exception raised
        }
    return jsonify(response)


@tntitem.route('/sidebar_results')
def show_sidebar_items():
    """Function to display the items in the sidebar"""
    markers = request.args.getlist('markers[]')

    my_collection = TntItems()
    my_collection.get(ids=markers)
    items = enrich_items(items=my_collection.items)
    return render_template(
        'sidebar_results.html',
        items=items)


@tntitem.route('/my', defaults={'page': 1})
@tntitem.route('/my/<page>')
@login_required
def show_items(page):
    """Function to display a list of items"""
    my_collection = TntItems()
    total = my_collection.search(author=g.user.id, sort='time.start', page=int(page)-1)
    for i, _ in enumerate(my_collection.items):
        if (isinstance(my_collection.items[i].data['images'], list) and
                len(my_collection.items[i].data['images'])):
            my_collection.items[i].data['images'] = my_collection.items[i].data['images'][0]

    return render_template(
        'item_list.html',
        items=my_collection.items,
        current_page=page,
        max_page=math.ceil(total/app.config['ES_DEFAULT_SIZE']))


@tntitem.route('/edit/<iditem>', methods=['GET', 'POST'])
@login_required
def edit_item(iditem):
    """Function to display the item edit page"""
    items = TntItems()
    items.get(ids=[iditem])
    if len(items.items) > 0:
        item = items.items[0]

    if request.method == 'POST':
        time_start = int(request.form['event_start'])
        time_end = int(request.form['event_end'])
        loc_latitude = float(request.form['latitude'])
        loc_longitude = float(request.form['longitude'])
        mes_images = []
        for mon_image in request.form.getlist('images-item[]'):
            if mon_image != "":
                mes_images.append(mon_image)
        mes_tags = request.form['tags'].split(',')
        for i, tag in enumerate(mes_tags):
            mes_tags[i] = tag.strip()
        # remove empty tags
        mes_tags = list(filter(None, mes_tags))
        app.logger.debug('Tags: %s' % mes_tags)

        form = EditForm(
            request.form,
            images=mes_images,
            time_t=(time_start, time_end),
            location_d={'lat': loc_latitude, 'lon': loc_longitude},
            csrf_enabled=True)

        if form.validate_on_submit():
            try:
                item = TntItem(
                    _id=iditem,
                    location_d={'lat': loc_latitude, 'lon': loc_longitude},
                    time_t=(time_start, time_end),
                    data_d={
                        'title': form.title.data,
                        'body': form.body.data,
                        'author': g.user.id,
                        'tags': mes_tags,
                        'images': mes_images,
                        'location': form.location.data,
                        'instagram_id': form.instagram_id.data,
                        'unsplash_id': form.unsplash_id.data,
                        'original_url': form.original_url.data,

app/tntmap/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the maps actions
"""

# all the imports
from flask import Blueprint, render_template, request, redirect, url_for, g, flash
from app.tntitem.forms import SearchForm


# Define the blueprint: 'maps', set its url prefix: app.url
tntmap = Blueprint(
    'tntmap',
    __name__,
    url_prefix='/map',
    template_folder='templates',
    static_folder='../static')

@tntmap.route('/', defaults={'username': None})
@tntmap.route('/@<username>')
def show_map(username):
    """Function to display a map (with content)"""
    if not g.user.is_authenticated:
        if request.args.get('ref') == "producthunt":
            people = 'Hi Producthunters!'
        else:
            people = 'Hi, travelers, digital nomads, photographers, hospitality professionals!'
        flash('{} We all like to keep track of our travel history. There \'n Then displays your pictures in time and space directly on a map. So, create your personal map to share it with your community by registering!'.format(people), 'success')

    return render_template(
        'map.html',
        searchform=SearchForm(request.form, csrf_enabled=False),
        constraintAuthor=username)

app/tnttag/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the tag actions
"""

# all the imports
from flask import Blueprint, jsonify, request
from app.tnttag.models import TntTags, TntTag
from app.tnttag.utils import enrich_items


# Define the blueprint: 'maps', set its url prefix: app.url
tnttag = Blueprint(
    'tnttag',
    __name__,
    url_prefix='/tag',
    template_folder='templates',
    static_folder='../static')


@tnttag.route('/search')
def search_tags():
    """Function to search a list of tags"""
    my_collection = TntTags()
    my_collection.search(text=request.args.get('tag'))

    items = enrich_items(my_collection.items)

    return jsonify(items)

@tnttag.route('/add', methods=['GET'])
def add_tag():
    """Function to add a tag"""
    my_tag = TntTag(label=request.args.get('tag'))
    my_tag.save()

    return jsonify({'tag': str(my_tag)})

app/tntitem/templates/item_list.html
{% extends "layout.html" %}
{% block title %} - My TnTs{% endblock %}
{% block body %}
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('tntmap.show_map') }}">Home</a></li>
                <li class="active">Items list</li>
            </ol>
            <!--end breadcrumb-->
            <section class="page-title">
                <h1>My TnTs</h1>
            </section>
            <!--end page-title-->
            {% if session.instagram_sync_task_id %}
            <section>
                <div class="my-item">
                    <div class="description">
                        <div class="vertical-aligned-elements">
                            <div class="element width-30">
                                <h3><i class="fa fa-refresh"></i> Current Instagram sync</h3>
                            </div>
                            <div class="element">
                                <div class="" id="last_instasync"></div>
                            </div>
                        </div>
                    </div>
                    <!--end description-->
                </div>
            </section>
            <!--end last sync-->
            {% endif %}
            {% if session.unsplash_sync_task_id %}
            <section>
                <div class="my-item">
                    <div class="description">
                        <div class="vertical-aligned-elements">
                            <div class="element width-30">
                                <h3><i class="fa fa-refresh"></i> Current Unsplash sync</h3>
                            </div>
                            <div class="element">
                                <div class="" id="last_unsplasync"></div>
                            </div>
                        </div>
                    </div>
                    <!--end description-->
                </div>
            </section>
            <!--end last sync-->
            {% endif %}
            <section>
                <div class="my-items table-responsive">
                    <table class="table">
                        <tbody>
                        {% for item in items %}
                        <tr class="my-item">
                            <td>
                                <div class="image-wrapper">
                                    <a href="#" data-modal-external-file="{{ url_for('tntitem.show_modal_item', id=item._id) }}" data-target="modal-item" class="image">
                                        <div class="bg-transfer">
                                            <img src="{{ item.data.images }}">
                                        </div>
                                    </a>
                                </div>
                                <div class="info">
                                    <a href="#" data-modal-external-file="{{ url_for('tntitem.show_modal_item', id=item._id) }}" data-target="modal-item"><h2>{{ item.data.title }}</h2></a>
                                    <figure class="location">location: {{ item.data.location }}</figure>
                                </div>
                                <!--end info-->
                            </td>
                            <td class="last-edited">
                                <span class="last-edit">Start: {{ item.time.start | cdate }} / End: {{ item.time.end | cdate }}</span>
                                <div class="edit-options">
                                    <a href="#" data-modal-external-file="{{ url_for('tntitem.edit_item', iditem=item._id) }}" data-target="modal-edit" class="link icon"><i class="fa fa-edit"></i>Edit</a>
                                    <a href="#" data-modal-external-file="{{ url_for('tntitem.delete_modal', iditem=item._id) }}" data-target="modal-delete" class="link icon delete"><i class="fa fa-trash"></i>Delete</a>
                                </div>
                                <!--end edit-options-->
                            </td>
                        </tr>
                        <!--end my-item-->
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--end my-items-->
            </section>
            <section>
                <div class="center">
                    <nav aria-label="Page navigation">
                        {% set previous_page = current_page|int - 1 %}
                        {% set next_page = current_page|int + 1 %}
                        <ul class="pagination">
                            {% if previous_page < 1 %}
                            <li class="disabled previous">
                                <a href="" aria-label="Previous">
                            {% else %}
                            <li class="previous">
                                <a href="{{ url_for('tntitem.show_items', page=previous_page) }}" aria-label="Previous">
                            {% endif %}
                                    <i class="arrow_left"></i>
                                </a>
                            </li>
                        {% for i in range(1, (max_page+1)|int) %}
                            {% if i == current_page|int %}
                            <li class="active">
                            {% else %}
                            <li>
                            {% endif %}
                            <a href="{{ url_for('tntitem.show_items', page=i) }}">{{ i }}</a></li>
                        {% endfor %}
                            {% if next_page > max_page|int %}
                            <li class="disabled next">
                                <a href="" aria-label="Next">
                            {% else %}
                            <li class="next">
                                <a href="{{ url_for('tntitem.show_items', page=next_page) }}" aria-label="Next">
                            {% endif %}
                                    <i class="arrow_right"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </section>
        </div>
        <!--end container-->
{% endblock %}

app/tntitem/templates/modal_edit.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
<div class="modal-item-detail modal-dialog" role="document" data-latitude="{{ form.latitude.data }}" data-longitude="{{ form.longitude.data }}" data-address="{{ form.location.data }}">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/zabuto_calendar/1.2.1/zabuto_calendar.min.css" type="text/css">
    <div class="modal-content">
        <form id="itemedit" class="form inputs-underline itemedit" enctype="multipart/form-data" method="POST" action="{{ url_for('tntitem.edit_item', iditem=iditem) }}">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <div class="section-title">
                <h2>Title</h2>
                <div class="form-group">
                    {{ form.title(class="form-control", placeholder="Title") }}
                </div>
            </div>
            <!--end section-title-->
        </div>
        <!--end modal-header-->
        <div class="modal-body">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                {{ form.instagram_id(class="form-control") }}
                {{ form.unsplash_id(class="form-control") }}
                {{ form.original_url(class="form-control") }}
                {{ form.latitude(class="form-control") }}
                {{ form.longitude(class="form-control") }}

                <section>
                    <h3>Gallery</h3>
                    <div class="file-uploaded-images">
                        {% for image in form.images.data %}
                        <div class="image">
                            <!-- <figure><i class="fa fa-close" data-role="remove"></i></figure> -->
                            <img src="{{ image }}" alt="">
                            <input class="form-control" type="hidden" name="images-item[]" value="{{ image }}">
                        </div>
                        {% endfor %}
                        <input type="hidden" class="form-control" id="images" name="images">
                    </div>
                    <!--end form-group-->
                </section>
                <section>
                    <h3>Location</h3>
                    <div class="form-group">{{ form.location(class="form-control") }}</div>
                    <div class="map" id="map-modal"></div>
                    <!--end map-->
                </section>
                <!--end map-->
                <section>
                    <h3>Time</h3>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6">
                            <div id="event_start_message"></div>
                            <input type="text" class="form-control date-picker" id="event_start" name="event_start" placeholder="Start Date" data-date-format="yyyy-mm-dd" value="{{ form.event_start.data | cdate }}">
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div id="event_end_message"></div>
                            <input type="text" class="form-control date-picker" id="event_end" name="event_end" placeholder="End Date" data-date-format="yyyy-mm-dd" value="{{ form.event_end.data | cdate }}">
                        </div>
                    </div>
                </section>
                <!--end time-->
                <section>
                    <h3>Description</h3>
                    <div class="form-group">
                        {{ form.body(class="form-control") }}
                    </div>
                    <!--end form-group-->
                </section>
                <!--end description-->

                <section>
                    <h3>Tags</h3>
                    <div class="form-group">
                        <input class="form-control" data-role="tagsinput" name="tags" id="input-tags" value="{{ item.data.tags|join(', ') }}">
                        <script type="text/javascript">
                            $('#input-tags').selectize({
                                plugins: ['remove_button'],
                                persist: false,
                                createOnBlur: false,
                                valueField: 'tag',
                                labelField: 'tag',
                                searchField: ['tag'],
                                create: function(input, callback){
                                    $.ajax({
                                        url: "{{ url_for('tnttag.add_tag') }}",
                                        method: 'GET',
                                        dataType: 'json',
                                        data: { tag: input },
                                        error: function() {
                                            callback();
                                        },
                                        success: function (response) {
                                            return callback(response);
                                        }
                                    });
                                },
                                render: {
                                    option: function (item, escape) {
                                        return '<div>' + escape(item.tag) + '</div>';
                                    }
                                },
                                load: function(query, callback) {
                                    if (!query.length) return callback();
                                    $.ajax({
                                        url: "{{ url_for('tnttag.search_tags') }}",
                                        type: 'GET',
                                        dataType: 'json',
                                        data: {
                                            tag: query,
                                        },
                                        error: function() {
                                            callback();
                                        },
                                        success: function(res) {
                                            callback(res);
                                        }
                                    });
                                },
                            });
                        </script>
                    </div>
                    <!--end form-group-->
                </section>
                <!--end tags-->
<!-- 
                <section>
                    <h3>Comments</h3>
                    {% for comment in item.comments %}
                    <div class="review">
                        <div class="description">
                            <figure>
                                <span class="date"><i class="fa fa-user"></i>&nbsp;{{ comment.author }} | {{ comment.date | ctime }}</span>
                            </figure>
                            <p>{{ comment.text }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </section>
-->
                <hr>
                <section class="center">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-rounded" id="edit_button">Submit</button>
                    </div>
                    <!--end form-group-->
                </section>
        </div>
        <!--end modal-body-->
        </form>
        <!--end form-->
        <script type="text/javascript">
            $( "#itemedit" ).submit(function( event ) {
                var ts_start = new Date(document.getElementById('event_start').value).getTime()/1000;
                var ts_end = new Date(document.getElementById('event_end').value).getTime()/1000;

                if (isNaN(ts_start) || isNaN(ts_end)) {
                    if (isNaN(ts_start)) {
                        $('#event_start_message').html('<div class="alert alert-danger">Error with date</div>');
                    } else {
                        $('#event_start_message').html('');
                    }
                    if (isNaN(ts_end)) {
                        $('#event_end_message').html('<div class="alert alert-danger">Error with date</div>');
                    } else {
                        $('#event_end_message').html('');
                    }
                    event.preventDefault();
                } else {
                    document.getElementById('event_start').value = ts_start;
                    document.getElementById('event_end').value = ts_end;
                }

                var values = $('input[name="images-item[]"]').map(function(){
                   return this.value;
                }).get();
                document.getElementById('images').value = values;
            });
        </script>
    </div>
    <!--end modal-content-->
</div>
<!--end modal-dialog-->
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>