app/tntuser/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Forms for the user blueprint."""

from flask import g
from flask_wtf import FlaskForm
from wtforms import PasswordField, TextField, HiddenField
from wtforms.validators import DataRequired, Email, Length
from app.tntuser.models import User
from app.tntuser.utils import is_username_unique

class RegisterForm(FlaskForm):
    """Registration form."""

    email = TextField(
        'Email',
        validators=[DataRequired(), Email(), Length(min=6, max=254)]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=255)]
    )
    confirm_password = PasswordField(
        'Confirm Password',
        validators=[DataRequired(), Length(min=6, max=255)]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()

        if not initial_validation:
            return False
        email = User.query.filter_by(email=self.email.data).first()

        if email:
            self.email.errors.append('Email already registered')
            return False

        if self.password.data != self.confirm_password.data:
            self.confirm_password.errors.append('Passwords do not match')
            return False

        return True

class LoginForm(FlaskForm):
    """Login form."""

    email = TextField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(email=self.email.data).first()
        if not self.user:
            self.email.errors.append('Unknown email address')
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        if not self.user.active:
            self.email.errors.append('User not activated')
            return False
        return True

class ProfileForm(FlaskForm):
    """Profile form."""

    username = TextField('Username', id='username', validators=[])
    email = TextField('Email', validators=[Email()])

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(ProfileForm, self).validate()
        if not initial_validation:
            return False

        if not is_username_unique(self.username.data):
            self.username.errors.append('Username should be unique')
            return False

        self.user = User.query.filter_by(email=self.email.data).first()
        if not self.user:
            self.email.errors.append('Unknown email address')
            return False

        if not self.user.active:
            self.email.errors.append('User not activated')
            return False
        return True

class ChangePasswordForm(FlaskForm):
    """Reset password form."""

    current_password = PasswordField('Current Password', validators=[DataRequired()])
    new_password = PasswordField(
        'New Password', validators=[DataRequired(), Length(min=6, max=255)])
    confirm_new_password = PasswordField(
        'Confirm New Password', validators=[DataRequired(), Length(min=6, max=255)])

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(ChangePasswordForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.get_by_id(g.user.id)
        if not self.user:
            self.errors.append('Unknown user')
            return False

        if not self.user.check_password(self.current_password.data):
            self.current_password.errors.append('Invalid password')
            return False

        if self.new_password.data != self.confirm_new_password.data:
            self.confirm_new_password.errors.append('Passwords do not match')
            return False

        return True

class ResetPasswordForm(FlaskForm):
    """Reset password form."""

    email = TextField(
        'Email',
        validators=[DataRequired(), Email(), Length(min=6, max=254)]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(ResetPasswordForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(ResetPasswordForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(email=self.email.data).first()
        if not self.user:
            return False

        return True

class DeleteAccountForm(FlaskForm):
    """Delete account form."""

    uuid = HiddenField(
        'uuid',
        validators=[DataRequired()]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(DeleteAccountForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(DeleteAccountForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.get_by_uuid(uuid=self.uuid.data)
        if not self.user:
            return False

        return True

app/tntuser/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the user actions"""

# all the imports
import json
import requests
import uuid
from flask import Blueprint, render_template, redirect, url_for, request, flash, g, session, make_response, jsonify
from flask_login import login_required, login_user, logout_user
from app.resource import login_manager, db, get_instagram_api, get_unsplash_api
from app.tntuser.forms import RegisterForm, LoginForm, ProfileForm, \
    ChangePasswordForm, ResetPasswordForm, DeleteAccountForm
from app.tntuser.models import User
from app.tntuser.utils import generate_confirmation_token, confirm_token, send_email, \
    generate_password, is_username_unique, process_delete_user
from app import app


# Define the blueprint: 'tntuser', set its url prefix: app.url
tntuser = Blueprint(
    'tntuser',
    __name__,
    url_prefix='/user',
    template_folder='templates',
    static_folder='../static')

@tntuser.route('/register', methods=['GET', 'POST'])
def register():
    """Function to create a user from a registration form"""
    form = RegisterForm(request.form, csrf_enabled=True)
    if request.method == 'POST':
        if form.validate_on_submit():
            u = User(
                uuid=str(uuid.uuid4()),
                email=form.email.data,
                password=form.password.data,
                active=False
            )
            db.session.add(u)
            db.session.commit()

            token = generate_confirmation_token(
                u.email, app.config['SECRET_KEY'], app.config['SECURITY_PASSWORD_SALT'])
            confirm_url = app.config['ROOT_URL'] + url_for('tntuser.confirm_email', token=token)
            html = render_template('activate_email.html', confirm_url=confirm_url)
            subject = "TnT - Please confirm your email"
            send_email(app.config['MAIL_DEFAULT_SENDER'], u.email, subject, html)

            flash('A confirmation email has been sent via email.', 'success')
            return redirect(url_for('tntmap.show_map'))
        else:
            return render_template('register.html', form=form, error=form.errors)
    else:
        return render_template('register.html', form=form, error=form.errors)


@tntuser.route('/confirm/<token>', methods=['GET'])
def confirm_email(token):
    """Function to validate token and activate user account"""
    response = make_response(redirect(url_for('tntuser.profile')))

    try:
        email = confirm_token(
            token, app.config['SECRET_KEY'], app.config['SECURITY_PASSWORD_SALT'])
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    else:
        user = User.query.filter_by(email=email).first_or_404()
        if user.active:
            flash('Account already confirmed. Please login.', 'success')
        else:
            user.active = True
            response.set_cookie('tour', value="one", path=url_for('tntuser.profile'))
            db.session.add(user)
            db.session.commit()
            flash('You have confirmed your account. Thanks!', 'success')
            login_user(user)

    return response


@tntuser.route('/signin', methods=['GET', 'POST'])
def login():
    """Function to display the modal sign in form"""
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            login_user(form.user)
            redirect_url = request.args.get('next') or url_for('tntmap.show_map')
            return redirect(redirect_url)
    if form.errors:
        return render_template('signin.html', form=form, error=form.errors)
    return render_template('modal_signin.html', form=form, error=form.errors)


@tntuser.route('/reset_pass', methods=['GET', 'POST'])
def reset_password():
    """Function to reset the password"""
    if request.method == 'POST':
        form = ResetPasswordForm(request.form, csrf_enabled=True)
        if form.validate_on_submit():
            new_password = generate_password()
            u = User.query.filter_by(email=form.email.data).first()
            u.set_password(new_password)
            db.session.commit()

            html = render_template('new_password_email.html', password=new_password)
            subject = "Please confirm your email"
            send_email(app.config['MAIL_DEFAULT_SENDER'], u.email, subject, html)

            flash('Your password has been updated', 'success')

        return redirect(url_for('tntmap.show_map'))

    else:
        form = ResetPasswordForm(csrf_enabled=True)

    return render_template('modal_reset_password.html', form=form, error=form.errors)


@tntuser.route('/change_pass', methods=['POST'])
@login_required
def change_password():
    """Function to change the password"""
    form_reset = ChangePasswordForm(request.form, csrf_enabled=True)
    if form_reset.validate_on_submit():
        u = User.get_by_id(g.user.id)
        u.set_password(form_reset.new_password.data)
        db.session.commit()
        flash('Your password has been updated', 'success')
    else:
        flash('Unable to change your password', 'danger')

    return redirect(url_for('tntuser.profile'))


@tntuser.route('/check_username/<username>')
@login_required
def check_username(username):
    return jsonify({'unique': is_username_unique(username)})


@tntuser.route('/me', methods=['GET', 'POST'])
@login_required
def profile():
    """Function to display the profile form"""
    form_reset = ChangePasswordForm(csrf_enabled=True)

    if request.method == 'POST':
        form = ProfileForm(request.form, csrf_enabled=True)
        if form.validate_on_submit():
            u = User.get_by_id(g.user.id)
            u.username = form.username.data
            db.session.commit()
    else:
        form = ProfileForm(username=g.user.username, email=g.user.email, csrf_enabled=True)

    response = make_response(render_template(
        'profile.html',
        form=form, error=form.errors,
        form_reset=form_reset, error_reset=form_reset.errors))

    if request.cookies.get('tourState') != 'end':
        u = User.get_by_id(g.user.id)
        if u.username:
            if u.is_instagram:
                if u.items_count>0:
                    response.set_cookie('tour', value="three", path=url_for('tntitem.show_items'))
                else:
                    response.set_cookie('tour', value="two", path=url_for('tntuser.profile'))
            else:
                response.set_cookie('tour', value="oneplus", path=url_for('tntuser.profile'))
        else:
            response.set_cookie('tour', value="one", path=url_for('tntuser.profile'))

    return response


@tntuser.route('/instagram_connect')
@login_required
def instagram_connect():
    """Connect to Instagram"""
    instapi = get_instagram_api(
        app.config['INSTAGRAM_KEY'],
        app.config['INSTAGRAM_SECRET'],
        app.config['ROOT_URL'] + url_for('tntuser.instagram_callback'))
    url = instapi.get_authorize_url(scope=app.config['INSTAGRAM_SCOPE'])
    return redirect(url)


@tntuser.route('/instagram_callback')
@login_required
def instagram_callback():
    """Instagram will redirect users back to this route after successfully logging in"""
    code = request.args.get('code')
    response = make_response(redirect(url_for('tntuser.profile')))

    if code:
        try:
            r = requests.post("https://api.instagram.com/oauth/access_token", data={
                'client_id': app.config['INSTAGRAM_KEY'],
                'client_secret': app.config['INSTAGRAM_SECRET'],
                'grant_type': 'authorization_code',
                'redirect_uri': app.config['ROOT_URL'] + url_for('tntuser.instagram_callback'),
                'code': code})
        except requests.exceptions.ConnectionError as e:
            app.logger.error('unable to connect to Instagram - %s', e)
        except requests.exceptions.RequestException as e:
            app.logger.error('unable to connect to Instagram - %s', e)

        if r.status_code != 200:
            app.logger.debug('Could not get access token: %s', r.reason)
            flash('Unable to connect to Instagram', 'danger')

        else:
            retour = json.loads(r.text)
            access_token = retour.get('access_token')
            user = retour.get('user')

            if not access_token:
                flash('Unable to get an Instagram access token', 'danger')

            # Sessions are used to keep this data
            session['instagram_access_token'] = access_token
            session['instagram_user'] = user

            # Store the data in database too
            g.user.insta_id = user['id']
            g.user.insta_user = user['username']
            g.user.insta_token = access_token
            db.session.commit()

            response.set_cookie('tour', value="two", path=url_for('tntuser.profile'))

            flash('Instagram succesfully connected', 'success')
    else:
        flash('Unable to get a valid Instagram code', 'danger')

    return response


@tntuser.route('/instagram_disconnect')
@login_required
def instagram_disconnect():
    """Disconnect from Instagram"""
    g.user.insta_id = None
    g.user.insta_user = None
    g.user.insta_token = None
    db.session.commit()
    session['instagram_access_token'] = None
    session['instagram_user'] = None

    return redirect(url_for('tntuser.profile'))


@tntuser.route('/unsplash_connect')
@login_required
def unsplash_connect():
    """Connect to Unsplash"""
    unsplapi = get_unsplash_api(
        app.config['UNSPLASH_KEY'],
        app.config['UNSPLASH_SECRET'],
        app.config['ROOT_URL'] + url_for('tntuser.unsplash_callback'))
    url = unsplapi.auth().get_authentication_url(app.config['UNSPLASH_SCOPE'])
    return redirect(url)


@tntuser.route('/unsplash_callback')
@login_required
def unsplash_callback():
    """Unsplash will redirect users back to this route after successfully logging in"""
    code = request.args.get('code')

app/tntuser/templates/activate_email.html
<p>Welcome and thanks for creating an account at There 'n Then!</p>
<br>
<p>Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>To let us know if you have any issues, suggestions or feature request, please use : hello@therenthen.co</p>
<br>
<p>See you on the maps,</p>
<p>The Flying Trout</p>

app/tntuser/templates/modal_signin.html
<div class="modal-dialog width-400px" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <div class="section-title">
                <h2>Sign In</h2>
            </div>
        </div>
        <div class="modal-body">
            <form class="form inputs-underline" method="POST" action="{{ url_for('tntuser.login') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your email">
                </div>
                <!--end form-group-->
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" id="password" placeholder="Your password">
                </div>
                <div class="form-group center">
                    <button type="submit" class="btn btn-primary width-100">Sign In</button>
                </div>
                <!--end form-group-->
            </form>

            <hr>

            <a href="#" data-modal-external-file="{{ url_for('tntuser.reset_password') }}" data-target="modal-reset-password">I have forgot my password</a>
            <!--end form-->
        </div>
        <!--end modal-body-->
    </div>
    <!--end modal-content-->
</div>
<!--end modal-dialog-->

app/tntuser/templates/new_password_email.html
<p>Hi there,</p>
<p>Your There 'n Then password has been reset to:</p>
<br>
<p>{{ password }}</p>
<br>
<p>Now, run and change it!</p>
<p>The Flying Trout</p>

app/tntuser/templates/profile.html
{% extends "layout.html" %}
{% block title %} - My profile{% endblock %}
{% block body %}
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('tntmap.show_map') }}">Home</a></li>
                <li class="active">Profile</li>
            </ol>
            <!--end breadcrumb-->
            <section class="page-title center">
                <h1>Your Profile</h1>
            </section>
            <!--end page-title-->
            <section>
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3">
                        <form class="form inputs-underline" method="POST" action="{{ url_for('tntuser.profile') }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <section>
                                <div class="user-details box">
                                    <figure class="ribbon">{{ user.items_count }} TnTs</figure>
                                    <div class="user-image">
                                        <div class="image">
                                            <div class="bg-transfer"><img src="{{ user.email | gravatar }}" alt=""></div>
                                            <!--end bg-transfer-->
                                        </div>
                                        <!--end image-->

                                    </div>
                                    <!--end user-image-->
                                    <div class="description clearfix">
                                        <div class="form-group">
                                            {{ form.username.label }}
                                            {{ form.username(class="form-control", placeholder="Username") }}
                                            {% if error.username %}
                                            <div class="alert alert-danger" role="alert">
                                              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                              <span class="sr-only">Error:</span>
                                              {{ error.username|join('<br>') }}
                                            </div>
                                            {% endif %}
                                        </div>
                                        <figure>
                                            <div class="pull-left"><strong>Member since</strong></div>
                                            <div class="pull-right">{{ user.created_at.strftime('%d/%m/%Y') }}</div>
                                        </figure>
                                    </div>
                                    <!--end description-->
                                </div>
                            </section>
                            <!--end user-details-->
                            <section>
                                <h3>About You</h3>
                                <div class="row">
                                    <div class="col-md-12 col-sm-12">
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            {{ form.email.label }}
                                            {{ form.email(class="form-control", placeholder="Email") }}
                                            {% if error.email %}
                                            <div class="alert alert-danger" role="alert">
                                              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                              <span class="sr-only">Error:</span>
                                              {{ error.email|join('<br>') }}
                                            </div>
                                            {% endif %}
                                        </div>
                                        <!--end form-group-->
                                    </div>
                                    <!--end col-md-12-->
                                </div>
                                <!--end row-->
                            </section>
                            <section>
                                <h3>Your Social Networks</h3>
                                <div class="row">
                                    <div class="col-md-12 col-sm-12">
                                        <div class="form-group">
                                            {% if user.is_instagram %}
                                            <div class="col-md-6 col-sm-6">
                                                <input type="text" class="form-control" name="instragram" id="instragram" value="Connected in as {{ user.insta_user }}" readonly>
                                            </div>
                                            <!--end col-md-6-->
                                            <div class="col-md-3 col-sm-3">
                                                <a href="{{ url_for('tntitem.instagram_sync') }}" class="btn btn-primary btn-small btn-rounded" onclick="clickAndDisable(this);" id="instagram_refresh"><i class="fa fa-refresh"></i><span></span></a>
                                                <a href="{{ url_for('tntuser.instagram_disconnect') }}" class="btn btn-primary btn-small btn-rounded" onclick="clickAndDisable(this);" id="instagram_disconnect"><i class="fa fa-times"></i><span></span></a>
                                            </div>
                                            <!--end col-md-3-->
                                            {% else %}
                                            <label for="instagram">Instragram</label>
                                            <div class="pull-right"><a href="{{ url_for('tntuser.instagram_connect') }}" id="instagram_connect" class="link font-color-dark"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a></div>
                                            {% endif %}
                                        </div>
                                        <!--end form-group-->
                                    </div>
                                    <!--end col-md-12-->
                                </div>
                                <!--end row-->
                                <div class="row">
                                    <div class="col-md-12 col-sm-12">
                                        <div class="form-group">
                                            {% if user.is_unsplash %}
                                            <div class="col-md-6 col-sm-6">
                                                <input type="text" class="form-control" name="unsplash" id="unsplash" value="Connected in as {{ user.unsplash_user }}" readonly>
                                            </div>
                                            <!--end col-md-6-->
                                            <div class="col-md-6 col-sm-6">
                                                <a href="{{ url_for('tntitem.unsplash_sync') }}" class="btn btn-primary btn-small btn-rounded" onclick="clickAndDisable(this);" id="unsplash_refresh"><i class="fa fa-refresh"></i><span></span></a>
                                                <a href="{{ url_for('tntuser.unsplash_disconnect') }}" class="btn btn-primary btn-small btn-rounded" onclick="clickAndDisable(this);" id="unsplash_disconnect"><i class="fa fa-times"></i><span></span></a>
                                            </div>
                                            <!--end col-md-3-->
                                            {% else %}
                                            <label for="instagram">Unsplash</label>
                                            <div class="pull-right"><a href="{{ url_for('tntuser.unsplash_connect') }}" id="unsplash_connect" class="link font-color-dark"><i class="fa fa-camera fa-2x" aria-hidden="true"></i></a></div>
                                            {% endif %}
                                        </div>
                                        <!--end form-group-->
                                    </div>
                                    <!--end col-md-12-->
                                </div>
                                <!--end row-->
                            </section>
                            <section class="center">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-rounded">Save Changes</button>
                                </div>
                                <!--end form-group-->
                            </section>
                            <section class="center">
                                <div><a href="{{ url_for('tntuser.profile') }}" class="link" id="restartTour">Restart the tour</a></div>
                            </section>
                        </form>
                        <!--end form-->
                        <hr>
                    </div>
                    <!--end col-md-6-->
                </div>
                <!--end row-->
            </section>
            <section>
                <section>
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-md-offset-4 col-sm-offset-4">
                            <h3 class="center">Change Your Password</h3>
                            <form id="reset_password" class="form inputs-underline" method="POST" action="{{ url_for('tntuser.change_password') }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                <div class="form-group">
                                    {{ form_reset.current_password.label }}
                                    <input class="form-control" id="current_password" name="current_password" type="password" value="" required>
                                    {% if error_reset.current_password %}
                                    <div class="alert alert-danger" role="alert">
                                      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                      <span class="sr-only">Error:</span>
                                      {{ error_reset.current_password|join('<br>') }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--end form-group-->
                                <div class="form-group">
                                    {{ form_reset.new_password.label }}
                                    <input class="form-control" id="new_password" name="new_password" type="password" value="" required>
                                    {% if error_reset.new_password %}
                                    <div class="alert alert-danger" role="alert">
                                      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                      <span class="sr-only">Error:</span>
                                      {{ error_reset.new_password|join('<br>') }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--end form-group-->
                                <div class="form-group">
                                    {{ form_reset.confirm_new_password.label }}
                                    <input class="form-control" id="confirm_new_password" name="confirm_new_password" type="password" value="" required>
                                    {% if error_reset.confirm_new_password %}
                                    <div class="alert alert-danger" role="alert">
                                      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                      <span class="sr-only">Error:</span>
                                      {{ error_reset.confirm_new_password|join('<br>') }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--end form-group-->
                                <div class="form-group center">
                                    <button type="submit" class="btn btn-primary btn-framed btn-rounded btn-light-frame">Change Password</button>
                                </div>
                                <!--end form-group-->
                            </form>
                        </div>
                    </div>
                </section>
            </section>
            <section>
                <section class="center">
                    <div><a href="#" data-modal-external-file="{{ url_for('tntuser.delete_modal') }}" data-target="modal-delete-user" class="link font-color-red">Remove account</a></div>
                </section>

            </section>
        </div>
        <!--end container-->
{% endblock %}