app/tntpage/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Forms for the static pages."""

from flask_wtf import FlaskForm
from wtforms import TextField, TextAreaField
from wtforms.validators import DataRequired, Optional, Email
from app import app

class ContactForm(FlaskForm):
    """Contact form."""

    name = TextField(
        'Name',
        validators=[Optional()]
    )
    email = TextField(
        'Email',
        validators=[DataRequired(), Email()]
    )
    subject = TextField(
        'Subject',
        validators=[DataRequired()]
    )
    message = TextAreaField(
        'Message',
        validators=[DataRequired()]
    )

    def __init__(self, *args, **kwargs):
        """Init the form."""
        super(ContactForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        initial_validation = super(ContactForm, self).validate()

        if not initial_validation:
            app.logger.debug(self.errors)
            return False

        return True

app/tntpage/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the user actions
"""

# all the imports
from flask import Blueprint, render_template, redirect, url_for, g, request, flash, send_from_directory
from app.tntuser.forms import RegisterForm
from app.tntpage.forms import ContactForm
from app.tntuser.utils import send_email
from app import app


# Define the blueprint: 'maps', set its url prefix: app.url
tntpage = Blueprint('tntpage', __name__, template_folder='templates', static_folder='../static')


@tntpage.route('/')
def show_home():
    """Function to display the homepage if user not logged in"""
    if request.args.get('ref') == "producthunt":
        return redirect(url_for('tntmap.show_map', ref='producthunt'))
    else:
        return redirect(url_for('tntmap.show_map'))


@tntpage.route('/terms')
def show_terms():
    """Function to display the static terms and conditions page"""
    return render_template('terms.html')


@tntpage.route('/privacy')
def show_privacy():
    """Function to display the static privacy policy page"""
    return render_template('privacy.html')


@tntpage.route('/credits')
def show_credits():
    """Function to display the static credits page"""
    return render_template('credits.html')


@tntpage.route('/contact', methods=['GET', 'POST'])
def show_contact():
    """Function to display the static contact page"""
    if request.method == 'POST':
        form = ContactForm(request.form, csrf_enabled=True)
        if form.validate():
            body = render_template(
                'contact_mail.txt',
                content=form.message.data,
                user=form.name.data,
                email=form.email.data)
            send_email(
                app.config['MAIL_DEFAULT_SENDER'],
                app.config['MAIL_DEFAULT_CONTACT'],
                form.subject.data, body)
            flash('Your message has been sent, thanks!', 'success')
            return redirect(url_for('tntpage.show_contact'))

    else:
        form = ContactForm(csrf_enabled=True)

    return render_template(
        'contact.html',
        form=form,
        error=form.errors)



@tntpage.route('/robots.txt')
def show_robotstxt():
    """Function to return robots.txt file
    """
    return send_from_directory(app.static_folder, 'robots.txt')

app/tntuser/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the user actions"""

# all the imports
import json
import requests
import uuid
from flask import Blueprint, render_template, redirect, url_for, request, flash, g, session, make_response, jsonify
from flask_login import login_required, login_user, logout_user
from app.resource import login_manager, db, get_instagram_api, get_unsplash_api
from app.tntuser.forms import RegisterForm, LoginForm, ProfileForm, \
    ChangePasswordForm, ResetPasswordForm, DeleteAccountForm
from app.tntuser.models import User
from app.tntuser.utils import generate_confirmation_token, confirm_token, send_email, \
    generate_password, is_username_unique, process_delete_user
from app import app


# Define the blueprint: 'tntuser', set its url prefix: app.url
tntuser = Blueprint(
    'tntuser',
    __name__,
    url_prefix='/user',
    template_folder='templates',
    static_folder='../static')

@tntuser.route('/register', methods=['GET', 'POST'])
def register():
    """Function to create a user from a registration form"""
    form = RegisterForm(request.form, csrf_enabled=True)
    if request.method == 'POST':
        if form.validate_on_submit():
            u = User(
                uuid=str(uuid.uuid4()),
                email=form.email.data,
                password=form.password.data,
                active=False
            )
            db.session.add(u)
            db.session.commit()

            token = generate_confirmation_token(
                u.email, app.config['SECRET_KEY'], app.config['SECURITY_PASSWORD_SALT'])
            confirm_url = app.config['ROOT_URL'] + url_for('tntuser.confirm_email', token=token)
            html = render_template('activate_email.html', confirm_url=confirm_url)
            subject = "TnT - Please confirm your email"
            send_email(app.config['MAIL_DEFAULT_SENDER'], u.email, subject, html)

            flash('A confirmation email has been sent via email.', 'success')
            return redirect(url_for('tntmap.show_map'))
        else:
            return render_template('register.html', form=form, error=form.errors)
    else:
        return render_template('register.html', form=form, error=form.errors)


@tntuser.route('/confirm/<token>', methods=['GET'])
def confirm_email(token):
    """Function to validate token and activate user account"""
    response = make_response(redirect(url_for('tntuser.profile')))

    try:
        email = confirm_token(
            token, app.config['SECRET_KEY'], app.config['SECURITY_PASSWORD_SALT'])
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    else:
        user = User.query.filter_by(email=email).first_or_404()
        if user.active:
            flash('Account already confirmed. Please login.', 'success')
        else:
            user.active = True
            response.set_cookie('tour', value="one", path=url_for('tntuser.profile'))
            db.session.add(user)
            db.session.commit()
            flash('You have confirmed your account. Thanks!', 'success')
            login_user(user)

    return response


@tntuser.route('/signin', methods=['GET', 'POST'])
def login():
    """Function to display the modal sign in form"""
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            login_user(form.user)
            redirect_url = request.args.get('next') or url_for('tntmap.show_map')
            return redirect(redirect_url)
    if form.errors:
        return render_template('signin.html', form=form, error=form.errors)
    return render_template('modal_signin.html', form=form, error=form.errors)


@tntuser.route('/reset_pass', methods=['GET', 'POST'])
def reset_password():
    """Function to reset the password"""
    if request.method == 'POST':
        form = ResetPasswordForm(request.form, csrf_enabled=True)
        if form.validate_on_submit():
            new_password = generate_password()
            u = User.query.filter_by(email=form.email.data).first()
            u.set_password(new_password)
            db.session.commit()

            html = render_template('new_password_email.html', password=new_password)
            subject = "Please confirm your email"
            send_email(app.config['MAIL_DEFAULT_SENDER'], u.email, subject, html)

            flash('Your password has been updated', 'success')

        return redirect(url_for('tntmap.show_map'))

    else:
        form = ResetPasswordForm(csrf_enabled=True)

    return render_template('modal_reset_password.html', form=form, error=form.errors)


@tntuser.route('/change_pass', methods=['POST'])
@login_required
def change_password():
    """Function to change the password"""
    form_reset = ChangePasswordForm(request.form, csrf_enabled=True)
    if form_reset.validate_on_submit():
        u = User.get_by_id(g.user.id)
        u.set_password(form_reset.new_password.data)
        db.session.commit()
        flash('Your password has been updated', 'success')
    else:
        flash('Unable to change your password', 'danger')

    return redirect(url_for('tntuser.profile'))


@tntuser.route('/check_username/<username>')
@login_required
def check_username(username):
    return jsonify({'unique': is_username_unique(username)})


@tntuser.route('/me', methods=['GET', 'POST'])
@login_required
def profile():
    """Function to display the profile form"""
    form_reset = ChangePasswordForm(csrf_enabled=True)

    if request.method == 'POST':
        form = ProfileForm(request.form, csrf_enabled=True)
        if form.validate_on_submit():
            u = User.get_by_id(g.user.id)
            u.username = form.username.data
            db.session.commit()
    else:
        form = ProfileForm(username=g.user.username, email=g.user.email, csrf_enabled=True)

    response = make_response(render_template(
        'profile.html',
        form=form, error=form.errors,
        form_reset=form_reset, error_reset=form_reset.errors))

    if request.cookies.get('tourState') != 'end':
        u = User.get_by_id(g.user.id)
        if u.username:
            if u.is_instagram:
                if u.items_count>0:
                    response.set_cookie('tour', value="three", path=url_for('tntitem.show_items'))
                else:
                    response.set_cookie('tour', value="two", path=url_for('tntuser.profile'))
            else:
                response.set_cookie('tour', value="oneplus", path=url_for('tntuser.profile'))
        else:
            response.set_cookie('tour', value="one", path=url_for('tntuser.profile'))

    return response


@tntuser.route('/instagram_connect')
@login_required
def instagram_connect():
    """Connect to Instagram"""
    instapi = get_instagram_api(
        app.config['INSTAGRAM_KEY'],
        app.config['INSTAGRAM_SECRET'],
        app.config['ROOT_URL'] + url_for('tntuser.instagram_callback'))
    url = instapi.get_authorize_url(scope=app.config['INSTAGRAM_SCOPE'])
    return redirect(url)


@tntuser.route('/instagram_callback')
@login_required
def instagram_callback():
    """Instagram will redirect users back to this route after successfully logging in"""
    code = request.args.get('code')
    response = make_response(redirect(url_for('tntuser.profile')))

    if code:
        try:
            r = requests.post("https://api.instagram.com/oauth/access_token", data={
                'client_id': app.config['INSTAGRAM_KEY'],
                'client_secret': app.config['INSTAGRAM_SECRET'],
                'grant_type': 'authorization_code',
                'redirect_uri': app.config['ROOT_URL'] + url_for('tntuser.instagram_callback'),
                'code': code})
        except requests.exceptions.ConnectionError as e:
            app.logger.error('unable to connect to Instagram - %s', e)
        except requests.exceptions.RequestException as e:
            app.logger.error('unable to connect to Instagram - %s', e)

        if r.status_code != 200:
            app.logger.debug('Could not get access token: %s', r.reason)
            flash('Unable to connect to Instagram', 'danger')

        else:
            retour = json.loads(r.text)
            access_token = retour.get('access_token')
            user = retour.get('user')

            if not access_token:
                flash('Unable to get an Instagram access token', 'danger')

            # Sessions are used to keep this data
            session['instagram_access_token'] = access_token
            session['instagram_user'] = user

            # Store the data in database too
            g.user.insta_id = user['id']
            g.user.insta_user = user['username']
            g.user.insta_token = access_token
            db.session.commit()

            response.set_cookie('tour', value="two", path=url_for('tntuser.profile'))

            flash('Instagram succesfully connected', 'success')
    else:
        flash('Unable to get a valid Instagram code', 'danger')

    return response


@tntuser.route('/instagram_disconnect')
@login_required
def instagram_disconnect():
    """Disconnect from Instagram"""
    g.user.insta_id = None
    g.user.insta_user = None
    g.user.insta_token = None
    db.session.commit()
    session['instagram_access_token'] = None
    session['instagram_user'] = None

    return redirect(url_for('tntuser.profile'))


@tntuser.route('/unsplash_connect')
@login_required
def unsplash_connect():
    """Connect to Unsplash"""
    unsplapi = get_unsplash_api(
        app.config['UNSPLASH_KEY'],
        app.config['UNSPLASH_SECRET'],
        app.config['ROOT_URL'] + url_for('tntuser.unsplash_callback'))
    url = unsplapi.auth().get_authentication_url(app.config['UNSPLASH_SCOPE'])
    return redirect(url)


@tntuser.route('/unsplash_callback')
@login_required
def unsplash_callback():
    """Unsplash will redirect users back to this route after successfully logging in"""
    code = request.args.get('code')

app/tntpage/templates/contact.html
{% extends "layout.html" %}
{% block title %} - Contact{% endblock %}
{% block body %}
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('tntmap.show_map') }}">Home</a></li>
                <li class="active">Contact</li>
            </ol>
            <section class="page-title">
                <h1 class="pull-left">Contact</h1>
            </section>
            <!--end section-title-->
        </div>
        <!--end container-->
        <section class="block">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3">
                        <h3>Contact Information</h3>
                        <div class="box">
                            <address>
                                <figure>Carrefully handcrafted by</figure>
                                <strong>The Flying Trout</strong>
                                <br>
                                <br>
                                <strong>Email</strong>
                                <figure><a href="mailto:hello@therenthen.co">hello@therenthen.co</a></figure>
                            </address>
                        </div>
                    </div>
                    <!--end col-md-3-->
                    <div class="col-md-9 col-sm-9">
                        <h3>Form</h3>
                        <form class="form form-email inputs-underline" id="form-hero" method="POST">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <div class="row">
                                <div class="col-md-4 col-sm-4">
                                    <div class="form-group">
                                        {{ form.name.label }}
                                        {{ form.name(class="form-control", placeholder="Name") }}
                                        {% if error.name|length > 0 %}
                                        <p class="text-danger">{{ error.name|join('<br>') }}</p>
                                        {% endif %}
                                    </div>
                                    <!--end form-group-->
                                </div>
                                <!--end col-md-4-->
                                <div class="col-md-4 col-sm-4">
                                    <div class="form-group">
                                        {{ form.email.label }}
                                        {{ form.email(class="form-control", placeholder="Email") }}
                                        {% if error.email|length > 0 %}
                                        <p class="text-danger">{{ error.email|join('<br>') }}</p>
                                        {% endif %}
                                    </div>
                                    <!--end form-group-->
                                </div>
                                <!--end col-md-4-->
                                <div class="col-md-4 col-sm-4">
                                    <div class="form-group">
                                        {{ form.subject.label }}
                                        {{ form.subject(class="form-control", placeholder="Subject") }}
                                        {% if error.subject|length > 0 %}
                                        <p class="text-danger">{{ error.subject|join('<br>') }}</p>
                                        {% endif %}
                                    </div>
                                    <!--end form-group-->
                                </div>
                                <!--end col-md-4-->
                            </div>
                            <!--end row-->
                            <div class="form-group">
                                {{ form.message.label }}
                                {{ form.message(class="form-control", rows="4") }}
                                {% if error.message|length > 0 %}
                                <p class="text-danger">{{ error.message|join('<br>') }}</p>
                                {% endif %}
                            </div>
                            <!--end form-group-->
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary icon shadow">Send Message<i class="fa fa-caret-right"></i></button>
                            </div>
                            <!--end form-group-->
                        </form>
                    </div>
                    <!--end col-md-9-->
                </div>
                <!--end row-->
            </div>
            <!--end container-->
        </section>

{% endblock %}

app/tntpage/templates/credits.html
{% extends "layout.html" %}
{% block title %} - Credits{% endblock %}
{% block body %}
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('tntmap.show_map') }}">Home</a></li>
                <li class="active">Credits</li>
            </ol>
            <!--end breadcrumb-->
            <section class="page-title">
                <h1>Credits</h1>
            </section>
            <!--end page-title-->
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <section>
                        <p>This tool only exists thanks to (with random order):</p>
                        <ul>
                            <li><a href="https://themeforest.net/item/locations-multipurpose-directory-template/18536570">Locations</a> template</li>
                            <li><a href="https://thenounproject.com/gbeck419/">Greg Beck at the Noun Project</a> for the logo</li>
                            <li><a href="https://developers.google.com/maps/">Google Maps API</a> for all the map actions</li>
                            <li><a href="https://github.com/googlemaps/js-rich-marker">Richmarker</a></li>
                            <li><a href="https://github.com/googlemaps/js-marker-clusterer">Marker Cluster</a></li>
                            <li><a href="https://github.com/googlemaps/v3-utility-library/tree/master/infobox">Infobox</a></li>
                            <li><a href="https://getbootstrap.com/">Bootstrap</a></li>
                            <li><a href="https://jquery.com/">jQuery</a></li>
                            <li><a href="http://fontawesome.io/">Fontawesome</a></li>
                            <li><a href="https://owlcarousel2.github.io/OwlCarousel2/">Owl Carousel 2</a></li>
                            <li><a href="http://www.daterangepicker.com/">Date Range Picker</a></li>
                            <li><a href="https://github.com/jnicol/trackpad-scroll-emulator">Trackpad Scroll Emulator</a></li>
                            <li><a href="https://selectize.github.io/selectize.js/">Selectize</a></li>
                            <li><a href="https://jqueryui.com/">jQuery UI</a></li>
                            <li><a href="https://github.com/jquery/jquery-migrate">jQuery migrate</a></li>
                            <li><a href="http://bootstraptour.com/">Bootstrap Tour</a></li>
                            <li><a href="https://silviomoreto.github.io/bootstrap-select/">Boostrap Select</a></li>
                            <li><a href="https://jqueryvalidation.org/">jQuery Validation</a></li>
                            <li><a href="https://github.com/js-cookie/js-cookie">jQuery Cookie</a></li>
                            <li><a href="http://icheck.fronteed.com/">iCkeck</a></li>
                            <li><a href="https://momentjs.com/">Moment.js</a></li>
                            <li><a href="http://github.hubspot.com/pace/docs/welcome/">Pace</a></li>
                        </ul>
                        <p>And the backend is using (with random order):</p>
                        <ul>
                            <li><a href="http://flask.pocoo.org/">Flask</a></li>
                            <li><a href="https://flask-login.readthedocs.io/en/latest/">Flask-Login</a></li>
                            <li><a href="http://flask-sqlalchemy.pocoo.org/2.1/">Flask-SQLAlchemy</a></li>
                            <li><a href="https://flask-migrate.readthedocs.io/en/latest/">Flask Migrate</a></li>
                            <li><a href="https://flask-bcrypt.readthedocs.io/en/latest/">Flask BCrypt</a></li>
                            <li><a href="http://flask-wtf.readthedocs.io/en/stable/index.html">Flask WTF</a></li>
                            <li><a href="https://flask-script.readthedocs.io/en/latest/">Flask Script</a></li>
                            <li><a href="https://pythonhosted.org/Flask-Gravatar/">Flask-Gravatar</a></li>
                            <li><a href="https://flask-admin.readthedocs.io/en/latest/">Flask Admin</a></li>
                            <li><a href="http://www.celeryproject.org/">Celery</a></li>
                            <li><a href="https://redis.io/">Redis</a></li>
                            <li><a href="http://pythonhosted.org/itsdangerous/">itsdangerous</a></li>
                            <li><a href="http://docs.python-requests.org/en/master/">Requests</a></li>
                            <li><a href="https://www.elastic.co/products/elasticsearch">Elasticsearch</a></li>
                            <li><a href="https://www.sqlite.org/">SQLite</a></li>
                            <li><a href="http://gunicorn.org/">Gunicorn</a></li>
                            <li><a href="http://supervisord.org/">Supervisor</a></li>
                            <li><a href="https://nginx.org/">nginx</a></li>
                            <li><a href="http://www.debian.org/">Debian</a></li>
                            <li>Everything is running on a VPS hosted by <a href="https://www.ovh.com/">OVH</a></li>
                        </ul>
                    </section>
                    <section>
                        <p>Last updated: july, 2017</p>
                    </section>
                </div>
                <!--end col-md-12-->

            </div>
            <!--end row-->
        </div>

{% endblock %}

app/tntpage/templates/home.html
{% extends "layout.html" %}
{% block body %}
        <div class="container">
            <div class="row">
              <div class="col-md-8 col-sm-8 homeblock">
                <div class="homeblocktext">
                    <p align="center"><img class="img-responsive" src="{{ url_for('static', filename='img/homelogo.png') }}"><br></p>
                    <p class="homepunchline"><b>Explore places and time</b><br>Travelers, digital nomads, photographers, hospitality professionals: we all like to keep track of our travel history.</p>
                    <hr>
                    <div class="col-md-6 col-sm-6">
                        <div class="text-element">
                            <h4><i class="fa fa-search fa-2x" aria-hidden="true"></i> Explore a place back in time</h4>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="text-element">
                            <h4><i class="fa fa-comments fa-2x" aria-hidden="true"></i> Leave comment in time & place</h4>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="text-element">
                            <h4><i class="fa fa-map fa-2x" aria-hidden="true"></i> Recount your story on a map</h4>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="text-element">
                            <h4><i class="fa fa-globe fa-2x" aria-hidden="true"></i> Keep track of your travels</h4>
                        </div>
                    </div>
                </div>
                <div class="background-wrapper">
                    <div class="bg-transfer opacity-25">
                        <img src="{{ url_for('static', filename='img/backhome.png') }}" alt="">
                    </div>
                </div>
                <!--end background-wrapper-->
              </div>
              <div class="col-md-4 col-sm-4">
                <form class="form inputs-underline" method="POST" action="{{ url_for('tntuser.register') }}" id="registration_form">
                    <input name="_csrf_token" type="hidden" value="{{ csrf_token() }}">
                    <div class="form-group">
                        {{ form.email.label }}
                        {{ form.email(class="form-control") }}
                        {% if error.email %}
                        <div class="alert alert-danger" role="alert">
                          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                          <span class="sr-only">Error:</span>
                          {{ error.email|join('<br>') }}
                        </div>
                        {% endif %}
                    </div>
                    <!--end form-group-->
                    <div class="form-group">
                        {{ form.password.label }}
                        {{ form.password(class="form-control") }}
                        {% if error.password %}
                        <div class="alert alert-danger" role="alert">
                          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                          <span class="sr-only">Error:</span>
                          {{ error.password|join('<br>') }}
                        </div>
                        {% endif %}
                    </div>
                    <!--end form-group-->
                    <div class="form-group">
                        {{ form.confirm_password.label }}
                        {{ form.confirm_password(class="form-control") }}
                        {% if error.confirm_password %}
                        <div class="alert alert-danger" role="alert">
                          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                          <span class="sr-only">Error:</span>
                          {{ error.confirm_password|join('<br>') }}
                        </div>
                        {% endif %}
                    </div>
                    <!--end form-group-->
                    <div class="form-group center">
                        <button type="submit" class="btn btn-primary width-100">Register Now</button>
                    </div>
                    <!--end form-group-->
                </form>

                <hr>

                <p class="center note">By clicking on “Register Now” button you are accepting the <a href="{{ url_for('tntpage.show_terms') }}" class="underline">Terms of Use</a></p>
                <!--end form-->
              </div>
            </div>
        </div>
{% endblock %}