app/tntitem/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the items actions
"""

# all the imports
import math
from flask import Blueprint, render_template, redirect, url_for, jsonify, flash, g, request, escape, session, make_response
from flask_login import login_required
from app.tntitem.models import TntItems, TntItem, TntItemComment
from app.tntitem.forms import SearchForm, DeleteForm, EditForm
from app.tntuser.models import User
from app.tntitem.utils import sync_insta_items, sync_unsplash_items, enrich_items, get_geocode
from app.resource import db
from app import app

# Define the blueprint: 'maps', set its url prefix: app.url
tntitem = Blueprint(
    'tntitem',
    __name__,
    url_prefix='/item',
    template_folder='templates',
    static_folder='../static')


@tntitem.route('/search', methods=['GET', 'POST'])
def search_items():
    """Function to search a list of items"""
    my_collection = TntItems()
    form = SearchForm(request.args, csrf_enabled=False)
    # this is the result of a real search (from right-pane)
    if form.validate():
        geobounds = {}
        if form.place.data is not None and form.place.data != "":
            geoplace = get_geocode(place=form.place.data)
            if geoplace is not None and len(geoplace) > 0:
                geobounds = geoplace[0]['geometry']['bounds']
        _ = my_collection.search(
            text=form.keyword.data,
            tags=form.tags.data,
            geobounds=geobounds,
            start=form.event_start.data,
            end=form.event_end.data,
            sort='time.start')
    # this is a search from the map display
    else:
        if request.args.get('author') != 'None':
            myAuthor = User.get_by_username(request.args.get('author'))
        else:
            myAuthor = None
        if myAuthor is not None:
            myAuthorId = myAuthor.id
        else:
            myAuthorId = None
        if ('north_east_lat' in request.args and
                'north_east_lng' in request.args and
                'south_west_lat' in request.args and
                'south_west_lng' in request.args):
            geobounds = {
                'northeast':{
                    'lat': float(request.args.get('north_east_lat')),
                    'lng': float(request.args.get('north_east_lng'))
                },
                'southwest': {
                    'lat': float(request.args.get('south_west_lat')),
                    'lng': float(request.args.get('south_west_lng'))
                }
            }
            _ = my_collection.search(
                author=myAuthorId,
                geobounds=geobounds,
                sort='time.start')
        else:
            _ = my_collection.search(
                author=myAuthorId,
                sort='time.start')

    items = enrich_items(items=my_collection.items)
    return jsonify(items)


@tntitem.route('/data_sync')
@login_required
def data_sync():
    """Function to sync data from social accounts with local data"""
    u = User.get_by_id(g.user.id)
    if not u.is_instagram and not u.is_unsplash:
        flash('You need to connect your social account (Instagram/Unsplash)', 'danger')
        return redirect(url_for('tntuser.profile'))
    else:
        response = make_response(redirect(url_for('tntitem.show_items')))
        if u.is_instagram:
            if u.insta_last_id is None:
                response.set_cookie('tour', value="three", path=url_for('tntitem.show_items'))
            task = sync_insta_items.delay(u.id)
            session['instagram_sync_task_id'] = task.id
            flash('Instagram sync started', 'success')
        if u.is_unsplash:
            if u.unsplash_last_id is None:
                response.set_cookie('tour', value="three", path=url_for('tntitem.show_items'))
            task = sync_unsplash_items.delay(u.id)
            session['unsplash_sync_task_id'] = task.id
            flash('Unsplash sync started', 'success')

        return response


@tntitem.route('/instagram_sync') 
def instagram_sync(): 
    """Function to sync instagram account with local data""" 
    u = User.get_by_id(g.user.id) 
    if not u.is_instagram: 
        flash('You need to connect your Instagram account', 'danger') 
        return redirect(url_for('tntuser.profile')) 
    else: 
        response = make_response(redirect(url_for('tntitem.show_items'))) 
        if u.insta_last_id is None: 
            response.set_cookie('tour', value="three", path=url_for('tntitem.show_items')) 
        task = sync_insta_items.delay(u.id) 
        session['instagram_sync_task_id'] = task.id 
        flash('Instagram crawl started', 'success') 
        return response 

@tntitem.route('/unsplash_sync') 
@login_required 
def unsplash_sync(): 
    """Function to sync Unsplash account with local data""" 
    u = User.get_by_id(g.user.id) 
    if not u.is_unsplash: 
        flash('You need to connect your Unsplash account', 'danger') 
        return redirect(url_for('tntuser.profile')) 
    else: 
        response = make_response(redirect(url_for('tntitem.show_items'))) 
        task = sync_unsplash_items.delay(u.id) 
        session['unsplash_sync_task_id'] = task.id 
        flash('Unsplash crawl started', 'success') 
        return response 


@tntitem.route('/instasync_status/<task_id>')
@login_required
def instagram_sync_status(task_id):
    task = sync_insta_items.AsyncResult(task_id)
    if task.state == 'SUCCESS':
        session.pop('instagram_sync_task_id', None)

    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'total': 0,
            'status': 'Pending'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'total': task.info.get('total', 0),
            'status': task.info.get('status', '')
        }
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'total': 0,
            'status': str(task.info),  # this is the exception raised
        }
    return jsonify(response)


@tntitem.route('/unsplasync_status/<task_id>')
@login_required
def unsplash_sync_status(task_id):
    task = sync_unsplash_items.AsyncResult(task_id)
    if task.state == 'SUCCESS':
        session.pop('unsplash_sync_task_id', None)

    if task.state == 'PENDING':
        response = {
            'state': task.state,
            'total': 0,
            'status': 'Pending'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'total': task.info.get('total', 0),
            'status': task.info.get('status', '')
        }
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'total': task.info.get('total', 0),
            'status': str(task.info),  # this is the exception raised
        }
    return jsonify(response)


@tntitem.route('/sidebar_results')
def show_sidebar_items():
    """Function to display the items in the sidebar"""
    markers = request.args.getlist('markers[]')

    my_collection = TntItems()
    my_collection.get(ids=markers)
    items = enrich_items(items=my_collection.items)
    return render_template(
        'sidebar_results.html',
        items=items)


@tntitem.route('/my', defaults={'page': 1})
@tntitem.route('/my/<page>')
@login_required
def show_items(page):
    """Function to display a list of items"""
    my_collection = TntItems()
    total = my_collection.search(author=g.user.id, sort='time.start', page=int(page)-1)
    for i, _ in enumerate(my_collection.items):
        if (isinstance(my_collection.items[i].data['images'], list) and
                len(my_collection.items[i].data['images'])):
            my_collection.items[i].data['images'] = my_collection.items[i].data['images'][0]

    return render_template(
        'item_list.html',
        items=my_collection.items,
        current_page=page,
        max_page=math.ceil(total/app.config['ES_DEFAULT_SIZE']))


@tntitem.route('/edit/<iditem>', methods=['GET', 'POST'])
@login_required
def edit_item(iditem):
    """Function to display the item edit page"""
    items = TntItems()
    items.get(ids=[iditem])
    if len(items.items) > 0:
        item = items.items[0]

    if request.method == 'POST':
        time_start = int(request.form['event_start'])
        time_end = int(request.form['event_end'])
        loc_latitude = float(request.form['latitude'])
        loc_longitude = float(request.form['longitude'])
        mes_images = []
        for mon_image in request.form.getlist('images-item[]'):
            if mon_image != "":
                mes_images.append(mon_image)
        mes_tags = request.form['tags'].split(',')
        for i, tag in enumerate(mes_tags):
            mes_tags[i] = tag.strip()
        # remove empty tags
        mes_tags = list(filter(None, mes_tags))
        app.logger.debug('Tags: %s' % mes_tags)

        form = EditForm(
            request.form,
            images=mes_images,
            time_t=(time_start, time_end),
            location_d={'lat': loc_latitude, 'lon': loc_longitude},
            csrf_enabled=True)

        if form.validate_on_submit():
            try:
                item = TntItem(
                    _id=iditem,
                    location_d={'lat': loc_latitude, 'lon': loc_longitude},
                    time_t=(time_start, time_end),
                    data_d={
                        'title': form.title.data,
                        'body': form.body.data,
                        'author': g.user.id,
                        'tags': mes_tags,
                        'images': mes_images,
                        'location': form.location.data,
                        'instagram_id': form.instagram_id.data,
                        'unsplash_id': form.unsplash_id.data,
                        'original_url': form.original_url.data,

app/tntmap/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the maps actions
"""

# all the imports
from flask import Blueprint, render_template, request, redirect, url_for, g, flash
from app.tntitem.forms import SearchForm


# Define the blueprint: 'maps', set its url prefix: app.url
tntmap = Blueprint(
    'tntmap',
    __name__,
    url_prefix='/map',
    template_folder='templates',
    static_folder='../static')

@tntmap.route('/', defaults={'username': None})
@tntmap.route('/@<username>')
def show_map(username):
    """Function to display a map (with content)"""
    if not g.user.is_authenticated:
        if request.args.get('ref') == "producthunt":
            people = 'Hi Producthunters!'
        else:
            people = 'Hi, travelers, digital nomads, photographers, hospitality professionals!'
        flash('{} We all like to keep track of our travel history. There \'n Then displays your pictures in time and space directly on a map. So, create your personal map to share it with your community by registering!'.format(people), 'success')

    return render_template(
        'map.html',
        searchform=SearchForm(request.form, csrf_enabled=False),
        constraintAuthor=username)

app/tntopen/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the user actions
"""

# all the imports
from flask import Blueprint, render_template, g, request, flash
from app.tntopen.utils import count_items, max_items, count_users
from app import app


# Define the blueprint: 'open', set its url prefix: app.url
tntopen = Blueprint(
    'tntopen',
    __name__,
    url_prefix='/open',
    template_folder='templates',
    static_folder='../static')


@tntopen.route('/')
def show_open():
    """Function to display the open"""
    items_count = count_items()
    items_max = max_items()
    users_count = count_users()
    return render_template(
        'open.html',
        items_count=items_count,
        items_max=items_max,
        users_count=users_count,
        )

app/tntpage/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""This modules handles all the user actions
"""

# all the imports
from flask import Blueprint, render_template, redirect, url_for, g, request, flash, send_from_directory
from app.tntuser.forms import RegisterForm
from app.tntpage.forms import ContactForm
from app.tntuser.utils import send_email
from app import app


# Define the blueprint: 'maps', set its url prefix: app.url
tntpage = Blueprint('tntpage', __name__, template_folder='templates', static_folder='../static')


@tntpage.route('/')
def show_home():
    """Function to display the homepage if user not logged in"""
    if request.args.get('ref') == "producthunt":
        return redirect(url_for('tntmap.show_map', ref='producthunt'))
    else:
        return redirect(url_for('tntmap.show_map'))


@tntpage.route('/terms')
def show_terms():
    """Function to display the static terms and conditions page"""
    return render_template('terms.html')


@tntpage.route('/privacy')
def show_privacy():
    """Function to display the static privacy policy page"""
    return render_template('privacy.html')


@tntpage.route('/credits')
def show_credits():
    """Function to display the static credits page"""
    return render_template('credits.html')


@tntpage.route('/contact', methods=['GET', 'POST'])
def show_contact():
    """Function to display the static contact page"""
    if request.method == 'POST':
        form = ContactForm(request.form, csrf_enabled=True)
        if form.validate():
            body = render_template(
                'contact_mail.txt',
                content=form.message.data,
                user=form.name.data,
                email=form.email.data)
            send_email(
                app.config['MAIL_DEFAULT_SENDER'],
                app.config['MAIL_DEFAULT_CONTACT'],
                form.subject.data, body)
            flash('Your message has been sent, thanks!', 'success')
            return redirect(url_for('tntpage.show_contact'))

    else:
        form = ContactForm(csrf_enabled=True)

    return render_template(
        'contact.html',
        form=form,
        error=form.errors)



@tntpage.route('/robots.txt')
def show_robotstxt():
    """Function to return robots.txt file
    """
    return send_from_directory(app.static_folder, 'robots.txt')

app/templates/error.html
{% extends "layout.html" %}
{% block body %}
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('tntmap.show_map') }}">Home</a></li>
                <li class="active">Error</li>
            </ol>
            <!--end breadcrumb-->
            <section class="page-title center error">
                <h1>{{ error.code }}</h1>
                <h2>Error</h2>
                <h3>{{ error.description }}</h3>
                <p>Whoops, we encountered an error, that's embarassing. An email has been sent to <a href="mailto:support@therenthen.co">support@therenthen.co</a> to check it out!</p>
            </section>
        </div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>

<html lang="en-US">
<head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','{{ gtm_key }}');</script>
    <!-- End Google Tag Manager -->
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="The Flying Trout">
    <meta name="description" content="Explore places and time! Travelers, digital nomads, hospitality professionals: we all like to keep track of our travel history.">
    <meta name="keywords" content="there-n-then, there, then, places, time, traveler, digital nomad, hospitality professional, travel, instagram, poi, point of interest, photo, pictures">
    <meta name="og:title" content="There 'n Then{% block title %}{% endblock %}">
    <meta name="og:image" content="{{ url_for('static', filename='img/sharelogo.png') }}">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon-32x32.png') }}" sizes="32x32">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon-16x16.png') }}" sizes="16x16">

    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='fonts/elegant-fonts.css') }}" rel="stylesheet" type="text/css">
    <link href='//fonts.googleapis.com/css?family=Lato:400,300,700,900,400italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.0/assets/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.25/daterangepicker.min.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/trackpad-scroll-emulator/1.0.8/trackpad-scroll-emulator.min.css" type="text/css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/css/selectize.bootstrap3.min.css" type="text/css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-tour/0.11.0/css/bootstrap-tour.min.css" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/pace.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">

    <title>There 'n Then{{ self.title() }}</title>

</head>

<body class="homepage">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id={{ gtm_key }}" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div class="page-wrapper">
    <header id="page-header">
        <nav>
            <div class="left">
                <a href="{{ url_for('tntmap.show_map') }}" class="brand"><img src="{{ url_for('static', filename='img/logo.png') }}" alt=""></a>
            </div>
            <!--end left-->
            <div class="right">
                <div class="primary-nav has-mega-menu">
                    <ul class="navigation">
                        {% if user.is_authenticated %}
                        {% if user.username %}
                        <li><a href="{{ url_for('tntmap.show_map', username=user.username)| replace('%40', '@') }}" id="mymap">My Map</a></li>
                        {% else %}
                        <li><a href="#" data-modal-external-file="{{ url_for('tntuser.show_missing_username') }}" data-target="modal-missing-username" id="mymap">My Map</a></li>
                        {% endif %}
                        <li><a href="{{ url_for('tntitem.show_items', page=1) }}">My TnT</a></li>
                        <li><a href="{{ url_for('tntuser.profile') }}">Profile</a></li>
                        {% endif %}
                    </ul>
                    <!--end navigation-->
                </div>
                <!--end primary-nav-->
                <div class="secondary-nav">
                    {% if user.is_authenticated %}
                    <a href="{{ url_for('tntuser.logout') }}">Logout</a>
                    {% else %}
                    <a href="#" data-modal-external-file="{{ url_for('tntuser.login') }}" data-target="modal-sign-in">Login</a>
                    <a href="{{ url_for('tntuser.register') }}" class="promoted">Register</a>
                    {% endif %}
                </div>
                <!--end secondary-nav-->
                {% if user.is_authenticated and user.is_social %}
                <a href="{{ url_for('tntitem.data_sync') }}" class="btn btn-primary btn-small btn-rounded icon shadow add-listing" onclick="clickAndDisable(this);" id="data_refresh"><i class="fa fa-refresh"></i><span>Sync content</span></a>
                {% endif %}
                <div class="nav-btn">
                    <i></i>
                    <i></i>
                    <i></i>
                </div>
            </div>
            <!--end right-->
        </nav>
        <!--end nav-->
    </header>
    <!--end page-header-->

    <div id="page-content">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block body %}{% endblock %}
    </div>
    <!--end page-content-->

    <footer id="page-footer">
        <div class="footer-wrapper">
            <div class="footer-navigation">
                <div class="container">
                    <div class="vertical-aligned-elements">
                        <div class="element width-50">Straight outta the river - <a href="https://the-flying-trout.com/" target="_blank">The Flying Trout</a>
                        <a href="https://twitter.com/ThereNThen" class="circle-icon"><i class="social_twitter"></i></a>
                        <a href="https://www.linkedin.com/company-beta/11043123" class="circle-icon"><i class="social_linkedin"></i></a>
                        </div>
                        <div class="element width-50 text-align-right">
                            <a href="{{ url_for('tntpage.show_home') }}">Home</a>
                            <a href="{{ url_for('tntpage.show_contact') }}">Contact</a>
                            <a href="{{ url_for('tntpage.show_terms') }}">Terms of Use</a>
                            <a href="{{ url_for('tntpage.show_privacy') }}">Privacy Policy</a>
                            <a href="{{ url_for('tntpage.show_credits') }}">Credits</a>
                            <a href="{{ url_for('tntopen.show_open') }}">Open</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--end page-footer-->
</div>
<!--end page-wrapper-->
<a href="#" class="to-top scroll" data-show-after-scroll="600"><i class="arrow_up"></i></a>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/js/bootstrap-select.js"></script>
<script type="text/javascript" src="//maps.google.com/maps/api/js?key={{ googlemaps_key }}&libraries=places"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/richmarker-compiled.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/markerclusterer_packed.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/infobox.js') }}"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.0/owl.carousel.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/trackpad-scroll-emulator/1.0.8/jquery.trackpad-scroll-emulator.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.25/daterangepicker.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/standalone/selectize.min.js"></script>
<script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js'></script>
<script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/bootstrap-tour/0.11.0/js/bootstrap-tour.min.js'></script>
<script type="text/javascript">var myShareURL = "{{ base_url }}{% if user.username %}{{ url_for('tntmap.show_map', username=user.username)| replace('%40', '@') }}{% else %}{{ url_for('tntmap.show_map') }}{% endif %}"</script>
<script type="text/javascript" src="{{ url_for('static', filename='js/custom.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/maps.js') }}"></script>

<script>
    var optimizedDatabaseLoading = 1;
    var constraintAuthor = "{{ constraintAuthor }}";
    var selfMap = {% if user.username == constraintAuthor %}true{% else %}false{% endif %};
    var automaticGeoLocation = {% if user.is_authenticated %}true{% else %}false{% endif %};
    var _latitude = 48.853421;
    var _longitude = 2.348785;
    var element = "map-homepage";
    var markerTarget = "modal"; // use "sidebar", "infobox" or "modal" - defines the action after click on marker
    var sidebarResultTarget = "modal"; // use "sidebar", "modal" or "new_page" - defines the action after click on marker
    var showMarkerLabels = false; // next to every marker will be a bubble with title
    var mapDefaultZoom = 14; // default zoom
    heroMap(_latitude,_longitude, element, markerTarget, sidebarResultTarget, showMarkerLabels, mapDefaultZoom, optimizedDatabaseLoading, constraintAuthor, selfMap, automaticGeoLocation);

    $(document).ready(function($) {
        if( $("#last_instasync").length ){
            updateLastSync("{{ url_for('tntitem.instagram_sync_status', task_id=session.instagram_sync_task_id) }}", $("#last_instasync"));
        };
        if( $("#last_unsplasync").length ){
            updateLastSync("{{ url_for('tntitem.unsplash_sync_status', task_id=session.unsplash_sync_task_id) }}", $("#last_unsplasync"));
        };
    });
</script>

</body>
